<?php

/**
 * WPThemeModule class file
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @link https://github.com/pradosoft/prado
 * @license https://github.com/pradosoft/prado/blob/master/LICENSE
 */

namespace WordPressThemer;

use Prado\Web\UI\TTheme;
use Prado\Util\TPluginModule;

/**
 * WPThemeModule class
 *
 * WPThemeModule changes the Theme to be loading a WordPress Theme
 * as a MasterClass Layout.  This is done by changing the Page.MasterClass
 * to one with a TForm and TContentPlaceHolder only.  All html is
 * generated by the WordPress Theme.  This is accomplished by replicating
 * wordpress theme functionality with minimal implementation and rendering
 * the theme out.  This module then breaks apart the theme into:
 * pre-THead HTML, inner THead HTML, pre-TForm HTML, post-TForm HTML,
 * pre-TForm end tag, post-TForm end tag; then places this html into the
 * page in the proper locations.
 *
 * This changes the MasterClass of of the page being themed to a custom
 * MasterClass for WordPress Theming.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 */
class WPThemeModule extends TPluginModule
{
	/** Map Type Road Map Constant */
	public const BEHAVIOR_NAME = "WPThemer";

	public function init($config)
	{
		parent::init($config);
		$this->getApplication()->attachEventHandler('onInitComplete', [$this, 'attachServiceHandler']);

		TTheme::attachClassBehavior(self::BEHAVIOR_NAME, 'WPThemeBehavior');
	}

	public function attachServiceHandler($sender, $param)
	{
		$service = $this->getService();
		if ($service->isa('Prado\Web\Services\TPageService')) {
			$service->attachEventHandler('onPreRunPage', [$this, 'attachPageHandler']);
		}
	}
	public function attachPageHandler($sender, $page)
	{
		$page->attachEventHandler('onPreInit', [$this, 'installWPTheme'], 20.9);
	}

	/**
	 * By this point, we are handling the end of onPreInit
	 * @param mixed $page
	 * @param mixed $param
	 */
	public function installWPTheme($page, $param)
	{
		if (($theme = $page->getTheme()) && $theme->isWordPressTheme()) {
			$page->setMasterClass('WPThemeMasterClassLayout');
		}
	}

}
